---
- name: Deploy Zabbix Server with PostgreSQL (Diploma)
  hosts: zabbix
  become: true
  vars:
    zabbix_db_password: zabbix  # Только для диплома!

  tasks:
    - name: Add Zabbix official APT repository
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Zabbix server, PostgreSQL, Apache, PHP and dependencies
      apt:
        name:
          - apache2
          - postgresql
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.1-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: Ensure PostgreSQL is running
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create Zabbix database user
      shell: sudo -u postgres psql -c "CREATE USER zabbix WITH PASSWORD '{{ zabbix_db_password }}' LOGIN;"
      args:
        creates: /etc/zabbix/.zabbix_user_created

    - name: Create Zabbix database
      shell: sudo -u postgres psql -c "CREATE DATABASE zabbix OWNER zabbix;"
      args:
        creates: /etc/zabbix/.zabbix_db_created

    - name: Import initial Zabbix schema (idempotent and verified)
      shell: |
        set -e
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | \
        sudo -u postgres psql -v ON_ERROR_STOP=1 zabbix
      args:
        creates: /etc/zabbix/.zabbix_schema_imported

    - name: Configure Zabbix server database password
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: 'DBPassword={{ zabbix_db_password }}'

    - name: Set proper permissions on Zabbix server config
      file:
        path: /etc/zabbix/zabbix_server.conf
        owner: root
        group: zabbix
        mode: '0640'

    - name: Ensure Zabbix log file exists
      file:
        path: /var/log/zabbix/zabbix_server.log
        state: touch
        owner: zabbix
        group: zabbix
        mode: '0644'

    - name: Set PHP timezone to Moscow
      lineinfile:
        path: /etc/php/8.1/apache2/php.ini
        regexp: '^;?date.timezone ='
        line: 'date.timezone = Europe/Moscow'
      notify: restart apache2

    - name: Create systemd override for Type=simple (avoids PID race condition)
      file:
        path: /etc/systemd/system/zabbix-server.service.d
        state: directory
        mode: '0755'

    - name: Configure systemd override to use Type=simple
      copy:
        content: |
          [Service]
          Type=simple
          PIDFile=
        dest: /etc/systemd/system/zabbix-server.service.d/override.conf
        mode: '0644'
      notify: daemon-reload and restart zabbix-server

    - name: Enable and start services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - apache2
        - zabbix-agent

  handlers:
    - name: restart apache2
      systemd:
        name: apache2
        state: restarted

    - name: daemon-reload and restart zabbix-server
      systemd:
        daemon_reload: yes
        name: zabbix-server
        state: restarted

